#include "SFZero/RIFF.cpp"
#include "SFZero/SF2.cpp"
#include "SFZero/SF2Generator.cpp"
#include "SFZero/SF2Reader.cpp"
#include "SFZero/SF2Sound.cpp"
#include "SFZero/SFZDebug.cpp"
#include "SFZero/SFZEG.cpp"
#include "SFZero/SFZReader.cpp"
#include "SFZero/SFZRegion.cpp"
#include "SFZero/SFZSample.cpp"
#include "SFZero/SFZSound.cpp"
#include "SFZero/SFZSynth.cpp"
#include "SFZero/SFZVoice.cpp"

