#!/bin/bash

$EDITOR 	\
	SFZeroEditor.{h,cpp} 	\
	SFZeroAudioProcessor.{h,cpp} 	\
	SFZSound.{h,cpp} 	\
	SFZRegion.{h,cpp} 	\
	SFZSample.{h,cpp} 	\
	SFZReader.{h,cpp} 	\
	SFZVoice.{h,cpp} 	\
	SFZEG.{h,cpp} 	\
	SFZSynth.{h,cpp} 	\
	SFZDebug.{h,cpp} 	\


