#!/bin/bash

$EDITOR 	\
	SFZeroEditor.{h,cpp} 	\
	SFZeroAudioProcessor.{h,cpp} 	\
	SFZSound.{h,cpp} 	\
	SFZRegion.{h,cpp} 	\
	SFZSample.{h,cpp} 	\
	SFZReader.{h,cpp} 	\
	SFZVoice.{h,cpp} 	\
	SFZEG.{h,cpp} 	\
	SFZSynth.{h,cpp} 	\
	SFZDebug.{h,cpp} 	\
	RIFF.{h,cpp} 	\
	SF2.{h,cpp} 	\
	SF2Generator.{h,cpp} 	\
	SF2Sound.{h,cpp} 	\
	SF2Reader.{h,cpp} 	\
	WinTypes.h 	\


