/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_A8E24640__
#define __PLUGINEDITOR_H_A8E24640__

#include "../JuceLibraryCode/JuceHeader.h"

class SFZeroAudioProcessor;


//==============================================================================
/**
*/
class SFZeroEditor  : public AudioProcessorEditor
{
public:
    SFZeroEditor(SFZeroAudioProcessor* ownerFilter);
    ~SFZeroEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint(Graphics& g);
};


#endif  // __PLUGINEDITOR_H_A8E24640__
